// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AttributeRouting.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Route Defaults")]
    public partial class RouteDefaultsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RouteDefaults.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Route Defaults", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I generate the routes defined in the subject controllers");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Route default specified with an attribute")]
        public virtual void RouteDefaultSpecifiedWithAnAttribute()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Route default specified with an attribute", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 7
 testRunner.When("I fetch the routes for the RouteDefaults controller\'s Index action");
#line 8
  testRunner.And("I fetch the routes for the HttpRouteDefaults controller\'s Get action");
#line 9
 testRunner.Then("the default for \"p1\" is \"variable\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Route default specified inline")]
        public virtual void RouteDefaultSpecifiedInline()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Route default specified inline", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 12
 testRunner.When("I fetch the routes for the RouteDefaults controller\'s InlineDefaults action");
#line 13
  testRunner.And("I fetch the routes for the HttpRouteDefaults controller\'s InlineDefaults action");
#line 14
 testRunner.Then("the route url is \"InlineDefaults/{hello}/{goodnight}\"");
#line 15
 testRunner.Then("the default for \"hello\" is \"sun\"");
#line 16
 testRunner.Then("the default for \"goodnight\" is \"moon\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Optional parameters specified with a url parameter token")]
        public virtual void OptionalParametersSpecifiedWithAUrlParameterToken()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Optional parameters specified with a url parameter token", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 19
 testRunner.When("I fetch the routes for the RouteDefaults controller\'s Optionals action");
#line 20
  testRunner.And("I fetch the routes for the HttpRouteDefaults controller\'s Optionals action");
#line 21
 testRunner.Then("the route url is \"Optionals/{p1}/{p2}/{p3}\"");
#line 22
  testRunner.And("the parameter \"p1\" is optional");
#line 23
  testRunner.And("the parameter \"p2\" is optional");
#line 24
  testRunner.And("the parameter \"p3\" is optional");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple routes with different defaults")]
        public virtual void MultipleRoutesWithDifferentDefaults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple routes with different defaults", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 27
 testRunner.When("I fetch the routes for the RouteDefaults controller\'s MultipleRoutes action");
#line 28
  testRunner.And("I fetch the routes for the HttpRouteDefaults controller\'s MultipleRoutes action");
#line 29
 testRunner.Then("the route named \"MultipleDefaults1\" has a default for \"p1\" of \"first\"");
#line 30
  testRunner.And("the route named \"MultipleDefaults2\" has a default for \"p1\" of \"second\"");
#line 31
  testRunner.And("the route named \"ApiMultipleDefaults1\" has a default for \"p1\" of \"first\"");
#line 32
  testRunner.And("the route named \"ApiMultipleDefaults2\" has a default for \"p1\" of \"second\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
