// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AttributeRouting.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Standard Usage")]
    public partial class StandardUsageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StandardUsage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Standard Usage", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes for an MVC controller")]
        [NUnit.Framework.TestCaseAttribute("GET", "Index", "", new string[0])]
        [NUnit.Framework.TestCaseAttribute("HEAD", "Index", "", new string[0])]
        [NUnit.Framework.TestCaseAttribute("POST", "Create", "Create", new string[0])]
        [NUnit.Framework.TestCaseAttribute("PUT", "Update", "Update/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("DELETE", "Destroy", "Destroy/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("GET", "Wildcards", "Wildcards/{*pathInfo}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("", "AnyVerb", "AnyVerb", new string[0])]
        public virtual void GeneratingRoutesForAnMVCController(string method, string action, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating routes for an MVC controller", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("I have registered the routes for the StandardUsageController");
#line 5
 testRunner.When(string.Format("I fetch the routes for the StandardUsageController\'s {0} action", action));
#line 6
 testRunner.Then(string.Format("the route is constrained to {0} requests", method));
#line 7
  testRunner.And(string.Format("the route url is \"{0}\"", url));
#line 8
  testRunner.And("the default for \"controller\" is \"StandardUsage\"");
#line 9
  testRunner.And(string.Format("the default for \"action\" is \"{0}\"", action));
#line 10
  testRunner.And("the namespace is \"AttributeRouting.Specs.Subjects\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes for an API controller")]
        [NUnit.Framework.TestCaseAttribute("GET", "Get", "api", new string[0])]
        [NUnit.Framework.TestCaseAttribute("HEAD", "Get", "api", new string[0])]
        [NUnit.Framework.TestCaseAttribute("OPTIONS", "Get", "api", new string[0])]
        [NUnit.Framework.TestCaseAttribute("POST", "Post", "api", new string[0])]
        [NUnit.Framework.TestCaseAttribute("OPTIONS", "Post", "api", new string[0])]
        [NUnit.Framework.TestCaseAttribute("PUT", "Put", "api/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("OPTIONS", "Put", "api/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("DELETE", "Delete", "api/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("OPTIONS", "Delete", "api/{id}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("GET", "Wildcards", "api/Wildcards/{*pathInfo}", new string[0])]
        [NUnit.Framework.TestCaseAttribute("", "AnyVerb", "api/AnyVerb", new string[0])]
        public virtual void GeneratingRoutesForAnAPIController(string method, string action, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating routes for an API controller", exampleTags);
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I have registered the routes for the HttpStandardUsageController");
#line 24
 testRunner.When(string.Format("I fetch the routes for the HttpStandardUsageController\'s {0} action", action));
#line 25
 testRunner.Then(string.Format("the route is constrained to {0} requests", method));
#line 26
  testRunner.And(string.Format("the route url is \"{0}\"", url));
#line 27
  testRunner.And("the default for \"controller\" is \"HttpStandardUsage\"");
#line 28
  testRunner.And(string.Format("the default for \"action\" is \"{0}\"", action));
#line 29
  testRunner.And("the namespace is \"AttributeRouting.Specs.Subjects.Http\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Responding to OPTIONS requests in an API controller")]
        public virtual void RespondingToOPTIONSRequestsInAnAPIController()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Responding to OPTIONS requests in an API controller", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("I have registered the routes for the HttpStandardUsageController");
#line 47
 testRunner.When("an OPTIONS request for \"api\" is made");
#line 48
 testRunner.Then("the Get action is matched");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
