<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	Localized Routes
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <h2>Localized Routes</h2>

    <p>This demo page localizes the route if you use en, es, or fr as your default browser culture.</p>
    <p>See the global.asax for configuration.</p>

    <a href="<%: Url.Action("Index") %>">This link was generated by MVC, and should point ot localized url.</a>

</asp:Content>