// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace AttributeRouting.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Defining Routes Via Conventions")]
    public partial class DefiningRoutesViaConventionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Conventions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Defining Routes Via Conventions", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I generate the routes defined in the subject controllers");
#line hidden
        }
        
        public virtual void GeneratingRoutesUsingACustomRouteConvention(string action, string method, string url)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating routes using a custom RouteConvention", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.When(string.Format("I fetch the routes for the RestfulRouteConventionTest controller\'s {0} action", action));
#line 8
 testRunner.Then(string.Format("the route url is \"{0}\"", url));
#line 9
  testRunner.And("the default for \"controller\" is \"RestfulRouteConventionTest\"");
#line 10
  testRunner.And(string.Format("the default for \"action\" is \"{0}\"", action));
#line 11
  testRunner.And(string.Format("the route for {0} is constrained to {1} requests", action, method));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Index()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Index", "GET", "RestfulRouteConventionTest");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_New()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("New", "GET", "RestfulRouteConventionTest/New");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Create()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Create", "POST", "RestfulRouteConventionTest");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Show()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Show", "GET", "RestfulRouteConventionTest/{id}");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Edit()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Edit", "GET", "RestfulRouteConventionTest/{id}/Edit");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Update()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Update", "PUT", "RestfulRouteConventionTest/{id}");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Delete()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Delete", "GET", "RestfulRouteConventionTest/{id}/Delete");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes using a custom RouteConvention")]
        public virtual void GeneratingRoutesUsingACustomRouteConvention_Destroy()
        {
            this.GeneratingRoutesUsingACustomRouteConvention("Destroy", "DELETE", "RestfulRouteConventionTest/{id}");
        }
    }
}
#endregion
