// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace AttributeRouting.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Route Builder")]
    public partial class RouteBuilderFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Routing.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Route Builder", "In order to generate routes for the MVC framework\r\nAs a user of the library\r\nI wa" +
                    "nt to have routes built according to my specifications", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I generate the routes defined in the subject controllers");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes for an action method")]
        public virtual void GeneratingRoutesForAnActionMethod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating routes for an action method", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.When("I fetch the routes for the RestfulTest controller\'s Index action");
#line 11
 testRunner.Then("the route url is \"Resources\"");
#line 12
  testRunner.And("the default for \"controller\" is \"RestfulTest\"");
#line 13
  testRunner.And("the default for \"action\" is \"Index\"");
#line 14
  testRunner.And("the namespace is \"AttributeRouting.Specs.Subjects\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generating routes with the restful http method attribute")]
        public virtual void GeneratingRoutesWithTheRestfulHttpMethodAttribute()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generating routes with the restful http method attribute", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.When("I fetch the routes for the RestfulTest controller");
#line 18
 testRunner.Then("the route for Index is constrained to GET requests");
#line 19
  testRunner.And("the route for Create is constrained to POST requests");
#line 20
  testRunner.And("the route for Update is constrained to PUT requests");
#line 21
  testRunner.And("the route for Destroy is constrained to DELETE requests");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Optional parameters specified with a url parameter token")]
        public virtual void OptionalParametersSpecifiedWithAUrlParameterToken()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Optional parameters specified with a url parameter token", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.When("I fetch the routes for the Test controller\'s OptionalParametersWithAToken action");
#line 25
 testRunner.Then("the route url is \"Test/Optionals/{p1}/{p2}/{p3}\"");
#line 26
  testRunner.And("the parameter p1 is optional");
#line 27
  testRunner.And("the parameter p2 is optional");
#line 28
  testRunner.And("the parameter p3 is optional");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple routes for a single action")]
        public virtual void MultipleRoutesForASingleAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple routes for a single action", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.When("I fetch the routes for the Test controller\'s MultipleRoutes action");
#line 32
 testRunner.Then("3 routes should be found");
#line 33
  testRunner.And("the 1st route url is \"Test/Multiple\"");
#line 34
  testRunner.And("the 2nd route url is \"Test/Multiple/Routes\"");
#line 35
  testRunner.And("the 3rd route url is \"Test/Multiple/Routes/Again\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Route defaults")]
        public virtual void RouteDefaults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Route defaults", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.When("I fetch the routes for the Test controller\'s Default action");
#line 39
 testRunner.Then("the default for \"param1\" is \"mapleleaf\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Regex route constraints specified with an attribute")]
        public virtual void RegexRouteConstraintsSpecifiedWithAnAttribute()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Regex route constraints specified with an attribute", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.When("I fetch the routes for the Test controller\'s Constraint action");
#line 43
 testRunner.Then("the parameter \"cat\" is constrained by the pattern \"^(kitty|meow-meow|purrbot)$\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple routes with different defaults and constraints for a single action")]
        public virtual void MultipleRoutesWithDifferentDefaultsAndConstraintsForASingleAction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple routes with different defaults and constraints for a single action", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.When("I fetch the routes for the Test controller\'s MultipleRoutesWithDefaultsAndConstra" +
                    "ints action");
#line 47
 testRunner.Then("the route named \"FirstDitty\" has a default for \"number\" of 666");
#line 48
  testRunner.And("the route named \"FirstDitty\" has a contraint on \"number\" of \"^\\d{4}$\"");
#line 49
  testRunner.And("the route named \"SecondDitty\" has a default for \"number\" of 777");
#line 50
  testRunner.And("the route named \"SecondDitty\" has a contraint on \"number\" of \"^\\d{1}$\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
